{
 "title": "AutoMuteUs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "automuteus_active_games", "legendFormat": "Active Gamse" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "automuteus_total_games", "legendFormat": "Games" },
    { "expr": "automuteus_total_guilds", "legendFormat": "Guilds" },
    { "expr": "automuteus_total_users", "legendFormat": "Users" }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active Games",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "automuteus_active_games" }
   ]
  },
  {
   "title": "Increase of Mute / Deafen By",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_worker\"}[2m])",
     "legendFormat": "Worker Bot"
    },
    {
     "expr": "rate(discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_capture\"}[2m])",
     "legendFormat": "Capture Bot"
    },
    {
     "expr": "rate(discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_official\"}[2m])",
     "legendFormat": "Primary Bot"
    }
   ]
  },
  {
   "title": "Mute / Deafen By",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_worker\"}",
     "legendFormat": "Worker Bot"
    },
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_capture\"}",
     "legendFormat": "Capture Bot"
    },
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_official\"}",
     "legendFormat": "Primary Bot"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\".*\"}[2m])) * 1)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Discord Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_worker\"}",
     "legendFormat": "Mute / Defean by Worker"
    },
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_capture\"}",
     "legendFormat": "Mute / Defean by Capture"
    },
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_official\"}",
     "legendFormat": "Mute / Defean by Primary"
    },
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"message_create_delete\"}",
     "legendFormat": "Post / Deleate Messages"
    },
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"message_edit\"}",
     "legendFormat": "Edit Messages"
    },
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"reaction_add_remove\"}",
     "legendFormat": "Add / Remove Reactions"
    },
    {
     "expr": "discord_requests_by_node_and_type{instance=~\".*\",job=\"discord_stats\",type=\"invalid_request\"}",
     "legendFormat": "Invalid Requests"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[2m]))",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[2m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[2m])) by (name)",
     "legendFormat": "r_{{name}}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[2m])) by (name)",
     "legendFormat": "t_{{name}}"
    }
   ]
  }
 ]
}