{
 "title": "AutoMuteUs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "automuteus_active_games", "legendFormat": "Active Gamse" }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "automuteus_total_games", "legendFormat": "Games" },
    { "expr": "automuteus_total_guilds", "legendFormat": "Guilds" },
    { "expr": "automuteus_total_users", "legendFormat": "Users" }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active Games",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "automuteus_active_games" }
   ]
  },
  {
   "title": "Increase of Mute / Deafen By",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_worker\"}[2m])",
     "legendFormat": "Worker Bot"
    },
    {
     "expr": "rate(discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_capture\"}[2m])",
     "legendFormat": "Capture Bot"
    },
    {
     "expr": "rate(discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_official\"}[2m])",
     "legendFormat": "Primary Bot"
    }
   ]
  },
  {
   "title": "Mute / Deafen By",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_worker\"}",
     "legendFormat": "Worker Bot"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_capture\"}",
     "legendFormat": "Capture Bot"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_official\"}",
     "legendFormat": "Primary Bot"
    }
   ]
  },
  {
   "title": "Mute / Deafen by",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discord_requests_by_type{type=\"mute_deafen_worker\"}",
     "legendFormat": "Worker Bot"
    },
    {
     "expr": "discord_requests_by_type{type=\"mute_deafen_capture\"}",
     "legendFormat": "Capture Bot"
    },
    {
     "expr": "discord_requests_by_type{type=\"mute_deafen_official\"}",
     "legendFormat": "Primary Bot"
    }
   ]
  },
  {
   "title": "Discord Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_worker\"}",
     "legendFormat": "Mute / Defean by Worker"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_capture\"}",
     "legendFormat": "Mute / Defean by Capture"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"mute_deafen_official\"}",
     "legendFormat": "Mute / Defean by Primary"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"message_create\"}",
     "legendFormat": "Post Messages"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"message_delete\"}",
     "legendFormat": "Deleate Messages"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"message_embed_create\"}",
     "legendFormat": "Post Embedded Messages"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"message_embed_edit\"}",
     "legendFormat": "Edit Embedded Messages"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"reaction_add\"}",
     "legendFormat": "Add Reactions"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"reaction_remove\"}",
     "legendFormat": "Remove Reactions"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"reaction_remove_all\"}",
     "legendFormat": "Remove All Reactions"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"create_guild_emoji\"}",
     "legendFormat": "Create Guild Emojis"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"guild\"}",
     "legendFormat": "Get Guilds"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"guild_channels\"}",
     "legendFormat": "Get Guild Channels"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"guild_emojis\"}",
     "legendFormat": "Get Guild Emojis"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"guild_member\"}",
     "legendFormat": "Get Guild Members"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"guild_roles\"}",
     "legendFormat": "Get Guild Roles"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"user_channel\"}",
     "legendFormat": "Get User Channels"
    },
    {
     "expr": "discord_requests_by_type{instance=~\".*\",job=\"discord_stats\",type=\"invalid_request\"}",
     "legendFormat": "Invalid Requests"
    }
   ]
  }
 ]
}